---
title: "Developing R packages with RStudio and Github"
---

<p class = "lead">
R packages offer a neat and organised way to share your code for others to use. Git and GitHub offer a neat and organised way to organise the development of your code, and share the files with others. RStudio combines the power of R and Git, so you can develop your packages using a single interface.
</p>

## The tools you need

In order to build packages, you need the following tools:

  1. R (version 4.0 ) with the following packages installed:
      - roxygen2
      - pkgbuild
      - remotes
      - devtools
  2. RStudio (version 1.3 or higher)
  3. RTools if on Windows (see further)
  4. git 
  5. an account on https://github.com/
  
You can read more on the installation in the articles below.

<div class="jumbotron">
  <h2>Installation of the tools you need.</h2>
  
  <p><a href="installrtools.html" class="btn btn-primary btn-lg" role="button">Installation of Rtools </a>
    <a href="installgit.html" class="btn btn-primary btn-lg" role="button">Installation of git </a>
    <a href="githubaccount.html" class="btn btn-primary btn-lg" role="button">Create an account on GitHub</a>
</div>

## Extra reading material

I don't intend to copy all the great content that is already available online. Below you find a couple of links to books and manuals that helped me find my way.

<div class="jumbotron">
  <h2>Extra reading material.</h2>
  
  <p><a href="https://happygitwithr.com/" class="btn btn-primary btn-lg" role="button">Git/GitHub for the useR (Jenny Bryan)</a>
<br>
  <p><a href="https://r-pkgs.org/" class="btn btn-primary btn-lg" role="button">R Packages (Hadley Wickham)</a>
<br>
  <p><a href="https://cran.r-project.org/doc/manuals/R-exts.html" class="btn btn-primary btn-lg" role="button">The manual on packages (R Core Team)</a>
<br>
<p><a href="https://docs.github.com/en/github" class="btn btn-primary btn-lg" role="button">Documentation of Github, the website</a>
<br>
<p><a href="https://docs.github.com/en/desktop" class="btn btn-primary btn-lg" role="button">Documentation of the GUI Github Desktop</a>
<br>
<p><a href="https://github.com/git-guides/" class="btn btn-primary btn-lg" role="button">The Git Guides: documentation on the git system</a>
</div>


